// <auto-generated />
namespace serveurJDRMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class itemEffet_Nom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(itemEffet_Nom));
        
        string IMigrationMetadata.Id
        {
            get { return "202004180832513_itemEffet_Nom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
